version: "3.8"
services:
  sqlserver:
    image: *****/mssql-server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Password1"
    ports:
      - "0.0.0.0:1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    healthcheck:
      test:
        - "CMD"
        - "/opt/mssql-tools/bin/sqlcmd"
        - "-U"
        - "SA"
        - "-P"
        - "Password1"
        - "-Q"
        - "SELECT 1"
      interval: 30s
      timeout: 10s
      retries: 9
      start_period: 30s
volumes:
  sqlserver: