name: ci

on:
  push:
    branches: 
    - main

jobs:
  push_to_registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract meta
        id: meta
        uses: docker/metadata-action
        with:
          images: serwus79/mssql-2019-fts:latest
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: serwus79/mssql-2019-fts:latest